version: "3"
services:
 mysql:
  image: mysql:5.7
  restart: always
  ports:
    - 3307:3306
  environment:
   MYSQL_ROOT_PASSWORD: Dem1UBHkTJbf4s
   MYSQL_DATABASE: estudo
   MYSQL_USER: root
   MYSQL_PASSWORD: Dem1UBHkTJbf4s
  networks: 
    - ${APPLICATION_NETWORK}
  volumes:
    - "./data:/var/lib/mysql"
 phpmyadmin_aplicacao:
  image: phpmyadmin/phpmyadmin
  deploy:
   placement:
    constraints: [node.role == manager]
  networks:
   - ${APPLICATION_NETWORK}
  environment:
   PMA_HOST: mysql
   PMA_PORT: 3306
  ports:
   - ${PHPMYADMIN_PORT}:80
  volumes: 
   - /sessions
 aplicacao_estudo:
  image: leolegends/microservices_php:latest
  deploy:
   replicas: 1
  # resources:
   # limits:
   #  cpus: "0.1"
   #  memory: 50M  
   restart_policy:
    condition: on-failure
  ports: 
   - ${HOST_PORT}:80
  volumes:
   - ${SERVICE_LOCATION}:/app
  environment:
   WEB_DOCUMENT_ROOT: /app/public
  networks:
   - ${APPLICATION_NETWORK}
networks: 
 app_network:
